Dockerfile, cico_run_EE_tests.sh, run_EE_tests.sh
installed mvn from SCL, better env vars propagation
=> Fix CI job

cico_run_EE_tests.sh
Preparation for integration to rhche build
=> Enhanced usage of source for EE tests

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, run_EE_tests.sh
Reverts redhat-developer/che-e2e-tests#41
=> Revert "Attempt to run k8 client without cert"

update_tenant.sh
It is not necessary to perform update if tag is already present
=> Improved updating of che server

update_tenant.sh
=> Added wait for Che server startup

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/ArquillianCheExtension.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceProviderProducer.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/resources/create-workspace-request.json, config, prepare_environment.sh, tests/pom.xml, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/JUnitTestExecutionTestCase.java, tests/src/test/java/redhat/che/functional/tests/MavenTestCase.java, tests/src/test/java/redhat/che/functional/tests/PomTestCase.java, tests/src/test/java/redhat/che/functional/tests/RunProjectTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/GitPopupTopMenu.java, tests/src/test/resources/arquillian.xml, update_tenant.sh
=> Offline token 1

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/WorkspacesTestCase.java
Test creation of second workspace if one is already running. Producer for CheWorkspaceProvider was created to produce configuration variables.
=> Workspace creation test

tests/src/test/java/redhat/che/functional/tests/WorkspacesTestCase.java
Fix after method in WorkspaceTestCase - anotation was missing.
=> Fix After method

tests/src/test/java/redhat/che/functional/tests/PomTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CodeEditorFragment.java, tests/src/test/java/redhat/che/functional/tests/fragments/Loader.java, tests/src/test/java/redhat/che/functional/tests/fragments/window/AskForValueDialog.java, tests/src/test/java/redhat/che/functional/tests/utils/ActionUtils.java
Now adding new dependency on exact line in <dependencies> block. Annotation error is checked not only for presence but exact text is checked to be sure this error is Bayesian. #73
=> Fixed tests of bayesian with pom.xml.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/rest/RestClient.java, config
For cases, when che-host is idled on openshift.
Signed-off-by: rhopp <rhopp@dhcp-10-40-5-4.brq.redhat.com>
=> Increased timeout when creating workspace.

config, update_tenant.sh
Signed-off-by: rhopp <rhopp@dhcp-10-40-5-17.brq.redhat.com>
=> Remove che image tag from config and download it from internet.

cico_run_EE_tests.sh, prepare_environment.sh
URL has changed. This inflicted prepare_environment.sh file.
=> WIP Change URL for retreving OS token.

tests/src/test/java/redhat/che/functional/tests/AnalyticsErrorMarkersTestCase.java, tests/src/test/java/redhat/che/functional/tests/customExceptions/MarkerNotPresentException.java, tests/src/test/java/redhat/che/functional/tests/fragments/CodeEditorFragment.java, tests/src/test/java/redhat/che/functional/tests/fragments/TabsPanel.java, tests/src/test/java/redhat/che/functional/tests/utils/ActionUtils.java
Errorneous dependecy is created, annotation error is verified. File is closed and reopened to check annotation error is still visible. Waiting for fix - expecting exception.
=> Analytics error markers

pom.xml, tests/pom.xml
Signed-off-by: rhopp <rhopp@dhcp-10-40-5-159.brq.redhat.com>
=> Update graphene and arquillian version.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java
Try-catch added when wkspc is changing its status.
=> Log for wkspc status change

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/util/Constants.java, arquillian-extension-che/src/main/resources/create-workspace-request-nodejs.json, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/AnalyticsErrorMarkersTestCase.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java, tests/src/test/java/redhat/che/functional/tests/PomTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CodeEditorFragment.java, tests/src/test/java/redhat/che/functional/tests/fragments/Project.java, tests/src/test/java/redhat/che/functional/tests/fragments/popup/ContextMenu.java, tests/src/test/java/redhat/che/functional/tests/utils/Constants.java
NodeJS bayesian test - expected Timeout exception (not finding bayesian error marker).
=> Bayesian nodejs

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java
Signed-off-by: rhopp <rhopp@redhat.com>
=> Fix URL for retrieving openshift token.

tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java
Signed-off-by: rhopp <rhopp@redhat.com>
=> Workaround - refreshing browser when wkspace not started correctly.

tests/src/test/java/redhat/che/functional/tests/AnalyticsErrorMarkersTestCase.java
=> Removed expected error from AnalyticsErrorMarkersTestsCase.

tests/src/test/java/redhat/che/functional/tests/MavenTestCase.java, tests/src/test/java/redhat/che/functional/tests/RunProjectTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsEditor.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsManager.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsManagerRow.java, tests/src/test/java/redhat/che/functional/tests/fragments/DebugLeftPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/LeftBar.java, tests/src/test/java/redhat/che/functional/tests/utils/ActionUtils.java
Test should create new mvn build command, successfully run it and remove it.
=> Rerun maven

arquillian-extension-che/src/main/resources/create-workspace-request-nodejs.json, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java
=> Changed nodejs stack.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/config/CheExtensionConfiguration.java, cico_run_EE_tests.sh, config_prod_preview, prepare_environment.sh, run_EE_tests.sh
=> Fixed scripts to be able to run against prod-preview.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/annotations/Workspace.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/resource/CheWorkspace.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/resource/Stack.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/resource/StackService.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/rest/RestClient.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java, tests/src/test/java/redhat/che/functional/tests/AnalyticsErrorMarkersTestCase.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/MavenTestCase.java, tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java, tests/src/test/java/redhat/che/functional/tests/PomTestCase.java, tests/src/test/java/redhat/che/functional/tests/WorkspacesTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CodeEditorFragment.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsEditor.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsManager.java, tests/src/test/java/redhat/che/functional/tests/fragments/TabsPanel.java, tests/src/test/java/redhat/che/functional/tests/suites/OrderedTestSuite.java, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java, tests/src/test/java/redhat/che/functional/tests/utils/ActionUtils.java
Workspace is reused when next test needs the same project and param removeAfterTest is false.
=> Create workspace only when needed

che-server-performance/.gitignore, che-server-performance/Readme.md, che-server-performance/pom.xml, che-server-performance/src/main/java/com/redhat/che/performance/ConstantSpeedMessageGeneratorExtension.java, che-server-performance/src/main/java/com/redhat/che/performance/OperateCheWorkspaceSender.java, che-server-performance/src/test/resources/log4j2.xml, che-server-performance/src/test/resources/messages/createWorkspace.json, che-server-performance/src/test/resources/scenarios/create-start-delete.xml, che-server-performance/src/test/resources/users.properties, pom.xml
=> Che soak tests added.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java
Using upstream master branch of che-starter again.
=> Change che-starter link to upstream.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java, tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java
=> Logging added in CheWorkspaceService and cleanup in PackageJsonTestCase.

che-start-workspace/jenkins-job/che-start-workspace.yml
=> che-start-workspace: Set jenkins job trigger to start once a day

che-start-workspace/README.md, che-start-workspace/jenkins-job/jenkins_jobs.ini
For easier updating our jenkins job, the file jenkins_jobs.ini was added. File README.md was update with instructions how to propagate changes to jenkins.
=> Adding jenkins_jobs.ini 

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/resources/create-workspace-request.json, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CodeEditorFragment.java, tests/src/test/java/redhat/che/functional/tests/fragments/EditorPart.java, tests/src/test/java/redhat/che/functional/tests/fragments/TabsPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/InfoPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/NotificationManager.java, tests/src/test/java/redhat/che/functional/tests/fragments/popup/Popup.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/ProfileTopMenu.java, tests/src/test/java/redhat/che/functional/tests/fragments/window/PreferencesWindow.java, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java
=> Run tests against rhche. Start refactoring of fucntional-tests.

.gitignore, che-start-workspace/_setenv.sh, che-start-workspace/jenkins-job/che-start-workspace.yml, che-start-workspace/osioperf.py, che-start-workspace/run.sh
Adding exit code equal to 1 when something fails. Waiting for workspace to change status on "STOPPED".
=> Performance failures

tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/MavenTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/CommandsManager.java, tests/src/test/java/redhat/che/functional/tests/fragments/LeftBar.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/ConsolesPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/InfoPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/TabsPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/WorkspaceStatusPage.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/MainMenuPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/WorkspaceTopMenu.java, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java
=> Refactor mechanism for checking whether workspace is up and running.

che-start-workspace/README.md, che-start-workspace/_zabbix-process-results.sh, che-start-workspace/osioperf.py, che-start-workspace/results-template.md, che-start-workspace/run.sh
Adding new metrics, changing final ERROR report. Adding check for "STOPPED" and "STOPPING" status of workspace in on_stop method.
=> Add metric time for stopping workspace

che-start-workspace/run.sh
The number was set to 9, but correct number is 8.
=> Wrong number of records set - fixed.

che-start-workspace/osioperf.py
added str() method to correctly concatenate string and integer
=> fix of concatenation string and integer

che-start-workspace/jenkins-job/che-start-workspace.yml
=> Set RUN_LOCALY to true

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/config/CheExtensionConfiguration.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/util/OpenShiftHelper.java, tests/src/test/java/redhat/che/functional/tests/suites/SmokeTestSuite.java
=> Modifying test suite to work against custom url

che-start-workspace/run.sh
Limit number of users to login to the number of users used for the test run.
=> che-start-workspace: Limit number of users to login

che-start-workspace/run.sh
=> Email notification on failure

che-start-workspace/jenkins-job/che-start-workspace.yml
Now results are sent to different zabbix hosts.
=> Zabbix host set via variable.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/config/CheExtensionConfiguration.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/util/OpenShiftHelper.java, cico/cico_run_EE_tests.sh, cico/config_rh_che_automated, cico/prepare_environment.sh, cico/run_EE_tests.sh, cico/validate_jwt_token.sh, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/suites/SmokeTestSuite.java, tests/src/test/resources/arquillian.xml
=> Modified run_EE_tests.sh to allow for custom server URL

che-start-workspace/__zabbix-process-load.sh, che-start-workspace/jenkins-job/che-start-workspace.yml, che-start-workspace/run.sh
After https://github.com/pmacik/openshiftio-performance-common/pull/1 is merged, this branch could be merged too. After merging the branch, update job on osioperf-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/che-start-workspace to be able to archive artifacts from new location. Changes were made, just use job builder to update.
=> Separating generated logs, updating job - archiving artifacts.

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/service/CheWorkspaceService.java, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java
=> Ft fixing tests

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/annotations/Workspace.java, tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/VertxPreviewUrlTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/infoPanel/NotificationManager.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/MainMenuPanel.java, tests/src/test/java/redhat/che/functional/tests/suites/OrderedTestSuite.java, tests/src/test/java/redhat/che/functional/tests/suites/StableTestSuite.java
New parameter for Workspace annotation added - "requireNewWorkspace". 
This test runs predefined "run" command and test preview url. It waits until service is available (one minute timeout) and than checks if the page requested by url contains "Vert.x HTTP Booster".
=> Preview url test

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, tests/src/test/java/redhat/che/functional/tests/EEVertxPushChange.java, tests/src/test/java/redhat/che/functional/tests/fragments/window/CommitToRepoWindow.java, tests/src/test/java/redhat/che/functional/tests/suites/E2ETestSuite.java, tests/src/test/java/redhat/che/functional/tests/utils/ActionUtils.java
Fixed using workspace by workspace name. Addin new test suite and new test for E2E tests.
Note: Should there be some other mechanism to specify workspace to be used? E. g. url, workspace id...
=> First test and suite.

tests/src/test/java/redhat/che/functional/tests/suites/SmokeTestSuite.java
=> Disabled GitTestCase from SmokeTestSuite

cico/run_EE_suite.sh, tests/src/test/java/redhat/che/functional/tests/EEVertxPushChange.java
=> Adding script to run E2ETestSuite.

che-start-workspace/osioperf.py
Log line starts with username.
=> Change PT logs

arquillian-extension-che/src/main/java/com/redhat/arquillian/che/CheWorkspaceManager.java, arquillian-extension-che/src/main/java/com/redhat/arquillian/che/provider/CheWorkspaceProvider.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/fragments/TabsPanel.java, tests/src/test/java/redhat/che/functional/tests/fragments/topmenu/GitPopupTopMenu.java, tests/src/test/java/redhat/che/functional/tests/fragments/window/BranchesWindow.java, tests/src/test/java/redhat/che/functional/tests/fragments/window/GitPushWindow.java
=> Fixed GitTestCase.

README.md, che-start-workspace/README.md, mount-volume/README.md, tests/README.md
READMEs should be up-to-date now.
=> Updates of READMEs of all projects.

job-definitions/che-start-workspace.yml
=> Fixing jobs definition.

cico/run_EE_suite.sh
Add line for building arquillian artifacts before executing functional tests.
=> Build arquillian artifacts.

cico/run_EE_suite.sh
Don't remove workspace when test ends.
=> Don't remove workspace

tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/GitTestCase.java, tests/src/test/java/redhat/che/functional/tests/PackageJsonTestCase.java, tests/src/test/java/redhat/che/functional/tests/VertxPreviewUrlTestCase.java
Fix periodical tests on 2, 2a and free-stg.
=> Fix periodical tests

tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java, tests/src/test/java/redhat/che/functional/tests/VertxPreviewUrlTestCase.java
Improvements to fix functional tests.
=> Fixing tests

tests/src/test/java/redhat/che/functional/tests/EEVertxPushChange.java
Test were sometimes failing because of pop-ups. This problem seems to be similar as the problem with Git test case, so I used the same approach to make it more stable. 
Wait for resolving project added.
=> Fix EE test

tests/src/test/java/redhat/che/functional/tests/AbstractCheFunctionalTest.java
Adding wait for all pop-ups to be shown (at one time) and then waiting till they close. Waiting for one minute, if not shown in that time (e. g. they are shown one by one), test continues.
=> Fix maven test

job-definitions/che-mount-volume.yml, job-definitions/che-start-workspace.yml, job-definitions/remove-workspaces.yml, remove-all-workspaces/README.md, remove-all-workspaces/get_active_tokens.sh, remove-all-workspaces/remove_workspaces.sh, remove-all-workspaces/run.sh
Script for removing all workspaces from specified accounts.
This script expects to have user.properties in place which should be like this:
```username;password;cluster```
where cluster is supposed to be set to "prod" or "prod-preview".
=> Add script for removing all workspaces from defined accounts.

cico/cico_run_EE_tests.sh
=> Change tag for che-functional-tests docker image.

job-definitions/che-mount-volume.yml, mount-volume/README.md, mount-volume/getopts_util.sh, mount-volume/pvc.yaml, mount-volume/run_test.sh, mount-volume/setup_pvc.sh, mount-volume/simple-pod-large.json, mount-volume/simple-pod.sh, mount-volume/zabbix.sh
At the begining it checks if PVC exists. If not, creates PVC and fill with files (if variable "FILL_PVC" is set to true by switch "-f"). 
Fixed timeout for starting/stopping pod. 
Adds some checks of failure (e. g. oc login).
=> Add PVC check and creation. Refactor scripts.

mount-volume/setup_pvc.sh
Now project was saved to /projects folder which was temporary. Moving cloning and installing project to /data/quickstart.
=> mount volume fix - update folder to save files on pvc

che-start-workspace/start-workspace-test-ephemeral.groovy, che-start-workspace/start-workspace-test.groovy
NOTE: Groovy pipelines don't support ternary operators like Java does
=> And another hotfix
